### ISSUE TITLE
What is this project, and how can I help?

### ISSUE THREAD

**Issue by banjomet** [AbstractMachinesLab/tree-sitter-erlang#4]
I was told to contribute here [when I asked how I could help work on Caramel](
https://github.com/AbstractMachinesLab/caramel/issues/25#issuecomment-744635427).

I am not really sure what this project is. I assume it is to write a parser for Erlang, but I don't understand why or how. I guess you want to move away from Menhir, why? The Erlang grammar [seems to be defined in this file that you are checking against](https://github.com/erlang/otp/blob/master/lib/stdlib/src/erl_parse.yrl), and it seems to me that you are trying to turn that .yrl file into a a grammar defined in JavaScript.

Why are you writing this in JavaScript, not OCaml?
The demo page spits out a weirdly formatted tree with numbers, it doesn't look like the S-Expression syntax I find in the test folder. Why is that?
What needs to happen?
How can, as a complete newbie idiot, help?

I think that adding to readme explaining what this project does, and adding a checklist of features that are needed/completed, would really help people have an idea of how they might contribute.

**Comment by leostera** [comment]
These are phenomenal questions. Thank you so much for bringing it up 🙌🏼 

Let me try to answer them, and if you agree on them being useful answers, we can add them to the README to get some direction 😄 

### I am not really sure what this project is

This is a flexible Grammar for Standard Erlang, written for the [tree-sitter parsing framework](https://tree-sitter.github.io/).

### why not write it in Menhir?

Writing the grammar in Menhir would mean its only usable from within the OCaml ecosystem. Writing it for tree-sitter means that any language that tree-sitter runs on will be able to parse Erlang code. tree-sitter [currently runs on 6 languages](https://tree-sitter.github.io/tree-sitter/#language-bindings) and I'm adding support for OCaml [here](https://github.com/AbstractMachinesLab/caramel/tree/main/ocaml-tree-sitter).

### why are you writing this in JavaScript, not OCaml?

Tree-sitter has a Javascript API for defining grammars, and it compiles these grammars into parsers. These parsers consist of a lot of generated C code.

### The demo page spits out a weirdly formatted tree with numbers, it doesn't look like the S-Expression syntax I find in the test folder.

I don't know. I didn't write the Playground, but the trees that are printed out are equivalent even if they aren't exactly S-expressions on both sides. Also the Playground shows you the line and column numbers for each tree-node. The tests don't show that.

### What needs to happen?

This parser needs to support ~100% of the Erlang grammar and then some more, to be usable for both parsing generated Erlang code, but also snippets of Erlang code that can be highlighed and parsed in editors liek Neovim.

Another goal in the horizon is to include this grammar into Github's Semantic, to allow Github to understand Erlang code.

### How can, as a complete newbie, help?

Asking this questions already helps a lot. Keep them coming!

Lastly, I'll try to put some time this weekend on making the README clearer of the current progress and goals of the parser so other people can contribute with more autonomy.

---

does this help?

**Comment by leostera** [comment]
Closing now :) let me know if I can help any more.
